// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import TiltController from "./tilt_controller"
application.register("tiltable", TiltController)

import ContentLoader from './content-loader_controller'
application.register('content-loader', ContentLoader)
